version: "3.8"

services:
  db-prod:
    image: postgres:13.7
    volumes:
      - ./tmp/db-vasquez-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    restart: always

  vasquez-prod:
    build:
      context: .
      dockerfile: docker/services/server/Dockerfile
    environment:
      DATABASE_NAME: "vasquez_services"
      RAILS_ENV: "production"
      RAILS_SERVE_STATIC_FILES: "true"
      DISABLE_DATABASE_ENVIRONMENT_CHECK: 1
    depends_on:
      - db-prod
    restart: always
    command: >
      sh -c "./wait-for-it.sh db-prod:5432 -- cron && sh ./run_server.sh"

  nginx-proxy-prod:
    build: ./docker/services/nginx
    ports:
      - 9092:9092
    depends_on:
      - vasquez-prod
    restart: always