version: "3.8"

services:
  db-dev:
    image: postgres:13.7
    volumes:
      - ./tmp/db-brendy-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: N0v@cgu@rd
      POSTGRES_USER: novacSystem
    ports:
      - 127.0.0.1:9731:5432

  agrodemi-prod:
    build:
      context: .
      dockerfile: docker/services/server/Dockerfile
    environment:
      ALMACEN: "panaderia_brendy"
      RAILS_ENV: "development"
      TULU: "N0v@cgu@rd"
      FRAGA: "novacSystem"
    depends_on:
      - db-dev
    volumes:
      - .:/usr/src/novac_server
    command: ["./wait-for-it.sh", "db-dev:5432", "--", "sh", "./run_server.sh"]

  nginx-proxy-dev:
    build: ./docker/services/nginx
    ports:
      - 9091:9091
    depends_on:
      - agrodemi-prod
