version: "3.8"

services:
  db-dev:
    image: postgres:13.7
    volumes:
      - ./tmp/db-vasquez-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

  vasquez-dev:
    build:
      context: .
      dockerfile: docker/services/server/Dockerfile
    environment:
      DATABASE_NAME: "vasquez_services"
      RAILS_ENV: "development"
    depends_on:
      - db-dev
    volumes:
      - .:/usr/src/novac_server
    command: ["./wait-for-it.sh", "db-dev:5432", "--", "sh", "./run_server.sh"]

  nginx-proxy-dev:
    build: ./docker/services/nginx
    ports:
      - 9092:9092
    depends_on:
      - vasquez-dev
