version: "3.8"

services:
  db-prod:
    image: postgres:13.7
    volumes:
      - ./tmp/db-agrodemi-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: N0v@cgu@rd
      POSTGRES_USER: novacSystem
    ports:
      - 127.0.0.1:9731:5432
    restart: always

  agrodemi-prod:
    build:
      context: .
      dockerfile: docker/services/server/Dockerfile
    environment:
      ALMACEN: "ADM"
      RAILS_ENV: "production"
      TULU: "N0v@cgu@rd"
      FRAGA: "novacSystem"
      RAILS_SERVE_STATIC_FILES: "true"
      DISABLE_DATABASE_ENVIRONMENT_CHECK: 1
    depends_on:
      - db-prod
    restart: always
    command: >
      sh -c "./wait-for-it.sh db-prod:5432 -- cron && sh ./run_server.sh"

  nginx-proxy-prod:
    build: ./docker/services/nginx
    ports:
      - 9090:9090
    depends_on:
      - agrodemi-prod
    restart: always