version: "3.8"

services:
  db-dev:
    image: postgres:13.7
    volumes:
      - ./tmp/$$DB_PATH$$:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

  $$NAME_IMG_DEV$$:
    build: .
    environment:
      DATABASE_NAME: "$$DATABASE_NAME$$"
      RAILS_ENV: "development"
    depends_on:
      - db-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/novac_server
    command: >
      sh -c "rm tmp/pids/server.pid ||
      rails server -b 0.0.0.0 --port 3000"
