import { FacturaI } from '@core/types/factura.types';
import { tipoComprobanteE } from '@core/constants/factura.utils';
import { documentTypeE } from '@core/types/document.types';

export const factura_31: FacturaI = {
  id_documento: '53502',
  fecha_vencimiento: '2025-05-15T08:00:00-04:00',
  numero_factura: 53502, // AGREGAR EN EL BACKEND
  condicion: 'Crédito',
  forma_pago: 'Efectivo',
  fecha_viaje: null,
  fecha_equivalente: '2025-04-15T08:00:00-04:00',
  pagada: false,
  balance: 146000,
  devuelta: 0,
  fecha_valida: null,
  tipo_factura_id: 3,
  numero_comprobante: 'E310000000001',
  costoYgasto: null,
  total_factura: 146000,
  Bruto: 150000,
  itbis: 0,
  descuento: 4000,
  estado: true,
  is_adelantada: false,
  is_viaje: false,  
  is_nota: false,
  movimientos_viaje: [],
  serie: 'normal',
  pre_factura: null,
  cotizacion: null,
  cliente_id: 3,
  cliente: {
    id: 3,
    nombre: 'Junior',
    apellido: 'Jose',
    direccion: 'Av. Imbert frente a bomba Petromovil, La Vega.',
    telefono: '809-555-1234',
    limite_credito: 30,
    documentos_de_identidad: [
      {
        id: 1,
        documento: '131880681',
        tipo: 'rnc',
        principal: true,
      },
    ],
  },
  TipoeCF: tipoComprobanteE.factura_de_credito_fiscal,
  document_type: documentTypeE.factura,
  detalle_facturas: [
    {
      key: '17447305427067',
      articulo: {
        id: 984,
        imagen_id: null,
        tipo_articulo_id: 2,
        nombre: 'MAIZ MOLIDO ',
        costo_principal: 810,
        precio_principal: 860,
        existencia: 3601695.7699999996,
        aviso_existencia: 1,
        codigo: '00984',
        fecha_ingreso: '2024-04-12',
        medida: 'Saco',
        is_detallable: true,
        medida_alerta: 'Libra',
        calcular_itbis: false,
        estado: true,
        is_combo: false,
        otros_costos: 0,
        vendido_en: 'Saco',
        is_materia_prima: true,
        contenido_articulos: [
          {
            id: 411,
            articulo_id: 984,
            referencia: null,
            costo: 8.1,
            precio: 8.6,
            cantidad: 100,
            medida: 'Libra',
            condicion: 'padre',
            calcular_itbis: false,
          },
        ],
        descripcion: 'Materia prima',
        contenido: { Saco: 100, Libra: 1 },
        cantidades: { Saco: 36016.9577, Libra: 3601695.7699999996 },
        calcular_saco: false,
        costos: {
          Saco: { costo: 810, precio: 860 },
          Libra: { costo: 8.1, precio: 8.6 },
        },
        tipo_articulo: {
          id: 2,
          descripcion: 'Materia prima',
          created_at: '2020-11-03T22:34:07.914Z',
          updated_at: '2020-11-03T22:34:07.914Z',
          tipo: 'venta_normal',
          codigo: 'materia_prima',
        },
      },
      unidades: [
        { value: 'Saco', precio: 860, costo: 810, cantidad: 100 },
        { value: 'Libra', precio: 8.6, costo: 8.1, cantidad: 1 },
      ],
      detalle_id: 150276,
      codigo: '00984',
      cantidad: 50,
      cantidad_initial: 50,
      cantidad_ant: null,
      descripcion: 'Maiz molido  ',
      unidad: 'Saco',
      precio: 860,
      costo: 810,
      descuento_valor: 1000,
      total: 42000,
      itbis: 0,
      cantidad_en_unidades: 5000,
      cantidad_en_unidades_initial: 5000,
      calcular_saco: false,
      is_defectuoso: false,
      is_devuelto: false,
      from_pre_factura: false,
      vende_sin_inventario: false,
      is_bad_price: false,
      actual_price: {
        Saco: { costo: 810, precio: 860 },
        Libra: { costo: 8.1, precio: 8.6 },
      },
      actual_price_value: '860.00',
      key_initial: null,
      producto_initial: null,
      articulo_id: 984,
      retirado: 5000,
      retirado_en_venta: 5000,
    },
    {
      key: '17447305423045',
      articulo: {
        id: 208,
        imagen_id: null,
        tipo_articulo_id: 2,
        nombre: 'Harina de Soya ',
        costo_principal: 1400,
        precio_principal: 1450,
        existencia: 2813544.352000001,
        aviso_existencia: 100,
        codigo: '00208',
        fecha_ingreso: '2020-11-19',
        medida: 'Quintal',
        is_detallable: true,
        medida_alerta: 'Quintal',
        calcular_itbis: false,
        estado: true,
        is_combo: false,
        otros_costos: 0,
        vendido_en: 'Saco',
        is_materia_prima: true,
        contenido_articulos: [
          {
            id: 35,
            articulo_id: 208,
            referencia: null,
            costo: 14,
            precio: 15,
            cantidad: 100,
            medida: 'Libra',
            condicion: 'padre',
            calcular_itbis: false,
          },
        ],
        descripcion: 'Materia prima',
        contenido: {
          Saco_100: 100,
          Saco_50: 50,
          Saco_25: 25,
          Quintal: 100,
          Libra: 1,
        },
        cantidades: { Quintal: 28135.443520000008, Libra: 2813544.352000001 },
        calcular_saco: true,
        costos: {
          Quintal: { costo: 1400, precio: 1450 },
          Libra: { costo: 14, precio: 15 },
          Saco_100: { costo: 1400, precio: 1450 },
          Saco_50: { costo: 700, precio: 725 },
          Saco_25: { costo: 350, precio: 362.5 },
        },
        tipo_articulo: {
          id: 2,
          descripcion: 'Materia prima',
          created_at: '2020-11-03T22:34:07.914Z',
          updated_at: '2020-11-03T22:34:07.914Z',
          tipo: 'venta_normal',
          codigo: 'materia_prima',
        },
      },
      unidades: [
        {
          value: 'Saco de 25 libras',
          precio: '362.50',
          costo: '350.00',
          cantidad: 25,
        },
        {
          value: 'Saco de 50 libras',
          precio: '725.00',
          costo: '700.00',
          cantidad: 50,
        },
        {
          value: 'Saco de 100 libras',
          precio: '1,450.00',
          costo: '1,400.00',
          cantidad: 100,
        },
        { value: 'Libra', precio: 15, costo: 14, cantidad: 1 },
      ],
      detalle_id: 150277,
      codigo: '00208',
      cantidad: 50,
      cantidad_initial: 50,
      cantidad_ant: null,
      descripcion: 'Harina de soya  ',
      unidad: 'Saco de 100 libras',
      precio: 1450,
      costo: 1400,
      descuento_valor: 2500,
      total: 70000,
      itbis: 0,
      cantidad_en_unidades: 5000,
      cantidad_en_unidades_initial: 5000,
      calcular_saco: true,
      is_defectuoso: false,
      is_devuelto: false,
      from_pre_factura: false,
      vende_sin_inventario: false,
      is_bad_price: false,
      actual_price: {
        Quintal: { costo: 1400, precio: 1450 },
        Libra: { costo: 14, precio: 15 },
        Saco_100: { costo: 1400, precio: 1450 },
        Saco_50: { costo: 700, precio: 725 },
        Saco_25: { costo: 350, precio: 362.5 },
      },
      actual_price_value: '1,450.00',
      key_initial: null,
      producto_initial: null,
      articulo_id: 208,
      retirado: 5000,
      retirado_en_venta: 5000,
    },
    {
      key: '17447305421020',
      articulo: {
        id: 166,
        imagen_id: null,
        tipo_articulo_id: 2,
        nombre: 'TRIGO',
        costo_principal: 585,
        precio_principal: 690,
        existencia: 250927.82,
        aviso_existencia: 30,
        codigo: '00166',
        fecha_ingreso: '2020-11-17',
        medida: 'Quintal',
        is_detallable: true,
        medida_alerta: 'Quintal',
        calcular_itbis: false,
        estado: true,
        is_combo: false,
        otros_costos: 0,
        vendido_en: 'Saco',
        is_materia_prima: true,
        contenido_articulos: [
          {
            id: 29,
            articulo_id: 166,
            referencia: null,
            costo: 5.85,
            precio: 6.9,
            cantidad: 100,
            medida: 'Libra',
            condicion: 'padre',
            calcular_itbis: false,
          },
        ],
        descripcion: 'Materia prima',
        contenido: {
          Saco_100: 100,
          Saco_50: 50,
          Saco_25: 25,
          Quintal: 100,
          Libra: 1,
        },
        cantidades: { Quintal: 2509.2782, Libra: 250927.82 },
        calcular_saco: true,
        costos: {
          Quintal: { costo: 585, precio: 690 },
          Libra: { costo: 5.85, precio: 6.9 },
          Saco_100: { costo: 585, precio: 690 },
          Saco_50: { costo: 292.5, precio: 345 },
          Saco_25: { costo: 146.25, precio: 172.5 },
        },
        tipo_articulo: {
          id: 2,
          descripcion: 'Materia prima',
          created_at: '2020-11-03T22:34:07.914Z',
          updated_at: '2020-11-03T22:34:07.914Z',
          tipo: 'venta_normal',
          codigo: 'materia_prima',
        },
      },
      unidades: [
        {
          value: 'Saco de 25 libras',
          precio: '172.50',
          costo: '146.25',
          cantidad: 25,
        },
        {
          value: 'Saco de 50 libras',
          precio: '345.00',
          costo: '292.50',
          cantidad: 50,
        },
        {
          value: 'Saco de 100 libras',
          precio: '690.00',
          costo: '585.00',
          cantidad: 100,
        },
        { value: 'Libra', precio: 6.9, costo: 5.85, cantidad: 1 },
      ],
      detalle_id: 150278,
      codigo: '00166',
      cantidad: 50,
      cantidad_initial: 50,
      cantidad_ant: null,
      descripcion: 'Trigo ',
      unidad: 'Saco de 100 libras',
      precio: 690,
      costo: 585,
      descuento_valor: 500,
      total: 34000,
      itbis: 0,
      cantidad_en_unidades: 5000,
      cantidad_en_unidades_initial: 5000,
      calcular_saco: true,
      is_defectuoso: false,
      is_devuelto: false,
      from_pre_factura: false,
      vende_sin_inventario: false,
      is_bad_price: false,
      actual_price: {
        Quintal: { costo: 585, precio: 690 },
        Libra: { costo: 5.85, precio: 6.9 },
        Saco_100: { costo: 585, precio: 690 },
        Saco_50: { costo: 292.5, precio: 345 },
        Saco_25: { costo: 146.25, precio: 172.5 },
      },
      actual_price_value: '690.00',
      key_initial: null,
      producto_initial: null,
      articulo_id: 166,
      retirado: 5000,
      retirado_en_venta: 5000,
    },
  ],
  FACTURA_DE: 18,
  tipo: 'venta',
  tiene_nota: false,
  vendedor_id: 2,
};
