export const factura_32 = {
  id_documento: '0',
  condicion: 'Contado',
  forma_pago: 'Efectivo',
  fecha_viaje: null,
  fecha_equivalente: null,
  pagada: true,
  balance: 0,
  devuelta: 1350,
  fecha_valida: null,
  tipo_factura_id: 23,
  numero_comprobante: null,
  costoYgasto: null,
  numero_factura: null,
  total_factura: 18650,
  Bruto: 18650,
  itbis: 0,
  descuento: 0,
  estado: true,
  is_adelantada: false,
  is_viaje: false,
  is_nota: false,
  movimientos_viaje: [],
  serie: 'electronica',
  pre_factura: null,
  cotizacion: null,
  cliente_id: null,
  NoCliente_nombre: 'Cliente contado',
  NoCliente_direccion: 'Autopista Duarte Km0 El Higüero, La Vega',
  detalle_facturas: [
    {
      key: '17383201316815',
      articulo: {
        id: 822,
        imagen_id: null,
        tipo_articulo_id: 2,
        nombre: 'MAIZ ENTERO AMERICANO 25LB',
        costo_principal: 200,
        precio_principal: 200,
        existencia: 142567,
        aviso_existencia: 1,
        codigo: '00822',
        fecha_ingreso: '2023-04-26',
        medida: 'Saco',
        is_detallable: false,
        medida_alerta: 'Libra',
        calcular_itbis: false,
        estado: true,
        is_combo: false,
        otros_costos: 0,
        vendido_en: 'Saco',
        is_materia_prima: true,
        contenido_articulos: [{ id: 351, articulo_id: 822, referencia: null, costo: 8, precio: 8, cantidad: 25, medida: 'Libra', condicion: 'padre', calcular_itbis: false }],
        descripcion: 'Materia prima',
        contenido: { Saco: 25, Libra: 1 },
        cantidades: { Saco: 5702.68, Libra: 142567 },
        calcular_saco: false,
        costos: { Saco: { costo: 200, precio: 200 }, Libra: { costo: 8, precio: 8 } },
        tipo_articulo: { id: 2, descripcion: 'Materia prima', created_at: '2020-11-03T22:34:07.914Z', updated_at: '2020-11-03T22:34:07.914Z', tipo: 'venta_normal', codigo: 'materia_prima' },
      },
      unidades: [{ value: 'Saco', precio: 200, costo: 200, cantidad: 25 }],
      detalle_id: null,
      codigo: '00822',
      cantidad: 1,
      cantidad_initial: 0,
      cantidad_ant: 1,
      descripcion: 'MAIZ ENTERO AMERICANO 25LB',
      unidad: 'Saco',
      precio: 200,
      costo: 200,
      descuento_valor: 0,
      total: 200,
      itbis: 0,
      cantidad_en_unidades: 25,
      cantidad_en_unidades_initial: 0,
      calcular_saco: false,
      is_defectuoso: false,
      is_devuelto: false,
      from_pre_factura: false,
      vende_sin_inventario: false,
      is_bad_price: false,
      actual_price: null,
      actual_price_value: null,
      key_initial: null,
      producto_initial: null,
      articulo_id: 822,
      retirado: 25,
      retirado_en_venta: 25,
    },
    {
      key: '17383201412542',
      articulo: {
        id: 208,
        imagen_id: null,
        tipo_articulo_id: 2,
        nombre: 'Harina de Soya ',
        costo_principal: 1475,
        precio_principal: 1500,
        existencia: 162974.37200000102,
        aviso_existencia: 100,
        codigo: '00208',
        fecha_ingreso: '2020-11-19',
        medida: 'Quintal',
        is_detallable: true,
        medida_alerta: 'Quintal',
        calcular_itbis: false,
        estado: true,
        is_combo: false,
        otros_costos: 0,
        vendido_en: 'Saco',
        is_materia_prima: true,
        contenido_articulos: [{ id: 35, articulo_id: 208, referencia: null, costo: 14.75, precio: 15, cantidad: 100, medida: 'Libra', condicion: 'padre', calcular_itbis: false }],
        descripcion: 'Materia prima',
        contenido: { Saco_100: 100, Saco_50: 50, Saco_25: 25, Quintal: 100, Libra: 1 },
        cantidades: { Quintal: 1629.7437200000102, Libra: 162974.37200000102 },
        calcular_saco: true,
        costos: { Quintal: { costo: 1475, precio: 1500 }, Libra: { costo: 14.75, precio: 15 }, Saco_100: { costo: 1475, precio: 1500 }, Saco_50: { costo: 737.5, precio: 750 }, Saco_25: { costo: 368.75, precio: 375 } },
        tipo_articulo: { id: 2, descripcion: 'Materia prima', created_at: '2020-11-03T22:34:07.914Z', updated_at: '2020-11-03T22:34:07.914Z', tipo: 'venta_normal', codigo: 'materia_prima' },
      },
      unidades: [
        { value: 'Saco de 25 libras', precio: '375.00', costo: '368.75', cantidad: 25 },
        { value: 'Saco de 50 libras', precio: '750.00', costo: '737.50', cantidad: 50 },
        { value: 'Saco de 100 libras', precio: '1,500.00', costo: '1,475.00', cantidad: 100 },
        { value: 'Libra', precio: 15, costo: 14.75, cantidad: 1 },
      ],
      detalle_id: null,
      codigo: '00208',
      cantidad: 10,
      cantidad_initial: 0,
      cantidad_ant: 10,
      descripcion: 'Harina de Soya ',
      unidad: 'Saco de 100 libras',
      precio: 1500,
      costo: 1475,
      descuento_valor: 0,
      total: 15000,
      itbis: 0,
      cantidad_en_unidades: 1000,
      cantidad_en_unidades_initial: 0,
      calcular_saco: true,
      is_defectuoso: false,
      is_devuelto: false,
      from_pre_factura: false,
      vende_sin_inventario: false,
      is_bad_price: false,
      actual_price: null,
      actual_price_value: null,
      key_initial: null,
      producto_initial: null,
      articulo_id: 208,
      retirado: 1000,
      retirado_en_venta: 1000,
    },
    {
      key: '17383201473825',
      articulo: {
        id: 166,
        imagen_id: null,
        tipo_articulo_id: 2,
        nombre: 'TRIGO',
        costo_principal: 635,
        precio_principal: 690,
        existencia: 345059.65,
        aviso_existencia: 30,
        codigo: '00166',
        fecha_ingreso: '2020-11-17',
        medida: 'Quintal',
        is_detallable: true,
        medida_alerta: 'Quintal',
        calcular_itbis: false,
        estado: true,
        is_combo: false,
        otros_costos: 0,
        vendido_en: 'Saco',
        is_materia_prima: true,
        contenido_articulos: [{ id: 29, articulo_id: 166, referencia: null, costo: 6.35, precio: 6.9, cantidad: 100, medida: 'Libra', condicion: 'padre', calcular_itbis: false }],
        descripcion: 'Materia prima',
        contenido: { Saco_100: 100, Saco_50: 50, Saco_25: 25, Quintal: 100, Libra: 1 },
        cantidades: { Quintal: 3450.5965, Libra: 345059.65 },
        calcular_saco: true,
        costos: { Quintal: { costo: 635, precio: 690 }, Libra: { costo: 6.35, precio: 6.9 }, Saco_100: { costo: 635, precio: 690 }, Saco_50: { costo: 317.5, precio: 345 }, Saco_25: { costo: 158.75, precio: 172.5 } },
        tipo_articulo: { id: 2, descripcion: 'Materia prima', created_at: '2020-11-03T22:34:07.914Z', updated_at: '2020-11-03T22:34:07.914Z', tipo: 'venta_normal', codigo: 'materia_prima' },
      },
      unidades: [
        { value: 'Saco de 25 libras', precio: '172.50', costo: '158.75', cantidad: 25 },
        { value: 'Saco de 50 libras', precio: '345.00', costo: '317.50', cantidad: 50 },
        { value: 'Saco de 100 libras', precio: '690.00', costo: '635.00', cantidad: 100 },
        { value: 'Libra', precio: 6.9, costo: 6.35, cantidad: 1 },
      ],
      detalle_id: null,
      codigo: '00166',
      cantidad: 10,
      cantidad_initial: 0,
      cantidad_ant: 10,
      descripcion: 'TRIGO',
      unidad: 'Saco de 50 libras',
      precio: 345,
      costo: 317.5,
      descuento_valor: 0,
      total: 3450,
      itbis: 0,
      cantidad_en_unidades: 500,
      cantidad_en_unidades_initial: 0,
      calcular_saco: true,
      is_defectuoso: false,
      is_devuelto: false,
      from_pre_factura: false,
      vende_sin_inventario: false,
      is_bad_price: false,
      actual_price: null,
      actual_price_value: null,
      key_initial: null,
      producto_initial: null,
      articulo_id: 166,
      retirado: 500,
      retirado_en_venta: 500,
    },
  ],
  FACTURA_DE: 32,
  tipo: 'venta',
  tiene_nota: false,
};
