import { tipoComprobanteE } from '@core/constants/factura.utils';
import { NotaI } from '../core/types/notas.types';
import { factura_31 } from './factura_31';

export const nota_credito: NotaI = {
  cliente_id: 3,
  user_id: null,
  fecha_valida: '30/12/2022',
  numero_comprobante: 'E340000000001',
  tipo_factura_id: 5,
  total: 56800,
  TipoeCF: tipoComprobanteE.nota_de_credito,
  facturas_aplicadas: [
    {
      cabecera_factura_id: 53502,
      total: 56800,
      detalles_facturas_notas: [
        {
          articulo_id: 984,
          articulo: {
            id: 984,
            imagen_id: null,
            tipo_articulo_id: 2,
            nombre: 'MAIZ MOLIDO ',
            costo_principal: 810,
            precio_principal: 860,
            existencia: 3601695.7699999996,
            aviso_existencia: 1,
            codigo: '00984',
            fecha_ingreso: '2024-04-12',
            medida: 'Saco',
            is_detallable: true,
            medida_alerta: 'Libra',
            calcular_itbis: false,
            estado: true,
            is_combo: false,
            otros_costos: null,
            vendido_en: 'Saco',
            created_at: '2024-04-12T15:32:05.170Z',
            updated_at: '2025-04-15T15:22:50.481Z',
            is_materia_prima: true,
            calcular_saco: false,
            contenido_articulos: [
              { id: 411, articulo_id: 984, referencia: null, costo: 8.1, precio: 8.6, cantidad: 100, medida: 'Libra', condicion: 'padre', calcular_itbis: null, created_at: '2024-04-12T15:32:05.212Z', updated_at: '2025-03-12T13:15:09.715Z' },
            ],
            formulas_productos_terminados: [],
            descripcion: 'MAIZ MOLIDO ',
          },
          unidad: 'Saco',
          itbis: 0,
          itbis_real: 0,
          costo: 810,
          precio: 860,
          precio_real: 860,
          descripcion: 'MAIZ MOLIDO ',
          total: 8400,
          cantidad_en_unidades: 1000,
          cantidad: 10,
          cantidad_origin: 50,
          detalle_factura_id: 150279,
          descuento: 1000,
          descuento_real: 0,
        },
        {
          articulo_id: 208,
          articulo: {
            id: 208,
            imagen_id: null,
            tipo_articulo_id: 2,
            nombre: 'Harina de Soya ',
            costo_principal: 1400,
            precio_principal: 1450,
            existencia: 2813544.352000001,
            aviso_existencia: 100,
            codigo: '00208',
            fecha_ingreso: '2020-11-19',
            medida: 'Quintal',
            is_detallable: true,
            medida_alerta: 'Quintal',
            calcular_itbis: false,
            estado: true,
            is_combo: false,
            otros_costos: null,
            vendido_en: 'Saco',
            created_at: '2020-11-19T18:55:30.290Z',
            updated_at: '2025-04-15T15:22:50.529Z',
            is_materia_prima: true,
            calcular_saco: true,
            contenido_articulos: [
              { id: 35, articulo_id: 208, referencia: null, costo: 14, precio: 15, cantidad: 100, medida: 'Libra', condicion: 'padre', calcular_itbis: null, created_at: '2020-11-19T18:55:30.362Z', updated_at: '2024-11-13T21:02:00.128Z' },
            ],
            formulas_productos_terminados: [],
            descripcion: 'Harina de Soya ',
          },
          unidad: 'Saco',
          itbis: 0,
          itbis_real: 0,
          costo: 1400,
          precio: 1450,
          precio_real: 1450,
          descripcion: ' (100 LBS) Harina de Soya ',
          total: 28000,
          cantidad_en_unidades: 2000,
          cantidad: 20,
          cantidad_origin: 50,
          detalle_factura_id: 150280,
          descuento: 2500,
          descuento_real: 0,
        },
        {
          articulo_id: 166,
          articulo: {
            id: 166,
            imagen_id: null,
            tipo_articulo_id: 2,
            nombre: 'TRIGO',
            costo_principal: 585,
            precio_principal: 690,
            existencia: 250927.82,
            aviso_existencia: 30,
            codigo: '00166',
            fecha_ingreso: '2020-11-17',
            medida: 'Quintal',
            is_detallable: true,
            medida_alerta: 'Quintal',
            calcular_itbis: false,
            estado: true,
            is_combo: false,
            otros_costos: null,
            vendido_en: 'Saco',
            created_at: '2020-11-17T17:00:26.589Z',
            updated_at: '2025-04-15T15:22:50.557Z',
            is_materia_prima: true,
            calcular_saco: true,
            contenido_articulos: [
              { id: 29, articulo_id: 166, referencia: null, costo: 5.85, precio: 6.9, cantidad: 100, medida: 'Libra', condicion: 'padre', calcular_itbis: null, created_at: '2020-11-17T17:00:26.591Z', updated_at: '2024-08-27T15:57:25.418Z' },
            ],
            formulas_productos_terminados: [],
            descripcion: 'TRIGO',
          },
          unidad: 'Saco',
          itbis: 0,
          itbis_real: 0,
          costo: 585,
          precio: 690,
          precio_real: 690,
          descripcion: ' (100 LBS) TRIGO',
          total: 20400,
          cantidad_en_unidades: 3000,
          cantidad: 30,
          cantidad_origin: 50,
          detalle_factura_id: 150281,
          descuento: 500,
          descuento_real: 0,
        },
      ],
    },
  ],
};
