import { tipoComprobanteE } from '@core/constants/factura.utils';
import { NotaI } from '../core/types/notas.types';
import { factura_31 } from './factura_31';
import { documentTypeE } from '@core/types/document.types';

export const nota_credito: NotaI = {
  cliente_id: 3,
  user_id: null,
  fecha_valida: '30/12/2022',
  numero_comprobante: 'E340000000001',
  numero_documento: '000056',
  tipo_factura_id: 5,
  total: 56800,
  TipoeCF: tipoComprobanteE.nota_de_credito,
  document_type: documentTypeE.nota,
  cliente: {
    id: 3,
    nombre: 'Junior',
    apellido: 'Jose',
    direccion: 'Av. Imbert frente a bomba Petromovil, La Vega.',
    telefono: '809-555-1234',
    limite_credito: 30,
    documentos_de_identidad: [
      {
        id: 1,
        numero: '131880681',
        tipo: 'rnc',
        principal: true,
      },
    ],
  },
  facturas_aplicadas: [
    {
      cabecera_factura_id: 53502,
      total: 56800,
      factura: factura_31,
      detalles_facturas_notas: [
        {
          articulo_id: 984,
          articulo: {
            id: 984,
            imagen_id: null,
            tipo_articulo_id: 2,
            nombre: 'MAIZ MOLIDO ',
            costo_principal: 810,
            precio_principal: 860,
            existencia: 3601695.7699999996,
            aviso_existencia: 1,
            codigo: '00984',
            fecha_ingreso: '2024-04-12',
            medida: 'Saco',
            is_detallable: true,
            medida_alerta: 'Libra',
            calcular_itbis: false,
            estado: true,
            is_combo: false,
            otros_costos: 0,
            vendido_en: 'Saco',
            is_materia_prima: true,
            contenido_articulos: [{ id: 411, articulo_id: 984, referencia: null, costo: 8.1, precio: 8.6, cantidad: 100, medida: 'Libra', condicion: 'padre', calcular_itbis: false }],
            formulas_productos_terminados: [],
            descripcion: 'MAIZ MOLIDO ',
            contenido: { Saco: 100, Libra: 1 },
            cantidades: { Saco: 36016.9577, Libra: 3601695.7699999996 },
            calcular_saco: false,
            costos: { Saco: { costo: 810, precio: 860 }, Libra: { costo: 8.1, precio: 8.6 } },
            tipo_articulo: { id: 2, descripcion: 'Materia prima', created_at: '2020-11-03T22:34:07.914Z', updated_at: '2020-11-03T22:34:07.914Z', tipo: 'venta_normal', codigo: 'materia_prima' },
          },
          unidad: 'Saco',
          itbis: 0,
          itbis_real: 0,
          costo: 810,
          precio: 860,
          precio_real: 860,
          descripcion: 'MAIZ MOLIDO ',
          total: 8400,
          cantidad_en_unidades: 1000,
          cantidad: 10,
          cantidad_origin: 50,
          detalle_factura_id: 150279,
          descuento: 1000,
          descuento_real: 0,
        },
        {
          articulo_id: 208,
          articulo: {
            id: 208,
            imagen_id: null,
            tipo_articulo_id: 2,
            nombre: 'Harina de Soya ',
            costo_principal: 1400,
            precio_principal: 1450,
            existencia: 2813544.352000001,
            aviso_existencia: 100,
            codigo: '00208',
            fecha_ingreso: '2020-11-19',
            medida: 'Quintal',
            is_detallable: true,
            medida_alerta: 'Quintal',
            calcular_itbis: false,
            estado: true,
            is_combo: false,
            otros_costos: 0,
            vendido_en: 'Saco',
            is_materia_prima: true,
            contenido_articulos: [{ id: 35, articulo_id: 208, referencia: null, costo: 14, precio: 15, cantidad: 100, medida: 'Libra', condicion: 'padre', calcular_itbis: false }],
            formulas_productos_terminados: [],
            descripcion: 'Harina de Soya ',
            contenido: { Saco_100: 100, Saco_50: 50, Saco_25: 25, Quintal: 100, Libra: 1 },
            cantidades: { Quintal: 28135.443520000008, Libra: 2813544.352000001 },
            calcular_saco: true,
            costos: { Quintal: { costo: 1400, precio: 1450 }, Libra: { costo: 14, precio: 15 }, Saco_100: { costo: 1400, precio: 1450 }, Saco_50: { costo: 700, precio: 725 }, Saco_25: { costo: 350, precio: 362.5 } },
            tipo_articulo: { id: 2, descripcion: 'Materia prima', created_at: '2020-11-03T22:34:07.914Z', updated_at: '2020-11-03T22:34:07.914Z', tipo: 'venta_normal', codigo: 'materia_prima' },
          },
          unidad: 'Saco',
          itbis: 0,
          itbis_real: 0,
          costo: 1400,
          precio: 1450,
          precio_real: 1450,
          descripcion: ' (100 LBS) Harina de Soya ',
          total: 28000,
          cantidad_en_unidades: 2000,
          cantidad: 20,
          cantidad_origin: 50,
          detalle_factura_id: 150280,
          descuento: 2500,
          descuento_real: 0,
        },
        {
          articulo_id: 166,
          articulo: {
            id: 166,
            imagen_id: null,
            tipo_articulo_id: 2,
            nombre: 'TRIGO',
            costo_principal: 585,
            precio_principal: 690,
            existencia: 250927.82,
            aviso_existencia: 30,
            codigo: '00166',
            fecha_ingreso: '2020-11-17',
            medida: 'Quintal',
            is_detallable: true,
            medida_alerta: 'Quintal',
            calcular_itbis: false,
            estado: true,
            is_combo: false,
            otros_costos: 0,
            vendido_en: 'Saco',
            is_materia_prima: true,
            contenido_articulos: [{ id: 29, articulo_id: 166, referencia: null, costo: 5.85, precio: 6.9, cantidad: 100, medida: 'Libra', condicion: 'padre', calcular_itbis: false }],
            formulas_productos_terminados: [],
            descripcion: 'TRIGO',
            contenido: { Saco_100: 100, Saco_50: 50, Saco_25: 25, Quintal: 100, Libra: 1 },
            cantidades: { Quintal: 2509.2782, Libra: 250927.82 },
            calcular_saco: true,
            costos: { Quintal: { costo: 585, precio: 690 }, Libra: { costo: 5.85, precio: 6.9 }, Saco_100: { costo: 585, precio: 690 }, Saco_50: { costo: 292.5, precio: 345 }, Saco_25: { costo: 146.25, precio: 172.5 } },
            tipo_articulo: { id: 2, descripcion: 'Materia prima', created_at: '2020-11-03T22:34:07.914Z', updated_at: '2020-11-03T22:34:07.914Z', tipo: 'venta_normal', codigo: 'materia_prima' },
          },
          unidad: 'Saco',
          itbis: 0,
          itbis_real: 0,
          costo: 585,
          precio: 690,
          precio_real: 690,
          descripcion: ' (100 LBS) TRIGO',
          total: 20400,
          cantidad_en_unidades: 3000,
          cantidad: 30,
          cantidad_origin: 50,
          detalle_factura_id: 150281,
          descuento: 500,
          descuento_real: 0,
        },
      ],
    },
  ],
};
