import { tipoComprobanteE } from '@core/constants/factura.utils';
import { NotaI } from '../core/types/notas.types';
import { factura_32 } from './factura_32';

export const nota_credito: NotaI = {
  cliente_id: 3,
  user_id: null,
  fecha_valida: '30/12/2022',
  numero_comprobante: 'E340000000001',
  tipo_factura_id: 5,
  total: 28300,
  TipoeCF: tipoComprobanteE.nota_de_credito,
  facturas_aplicadas: [
    {
      cabecera_factura_id: 53501,
      total: 28300,
      factura: factura_32,
      detalles_facturas_notas: [
        {
          articulo_id: 984,
          articulo: {
            id: 984,
            imagen_id: null,
            tipo_articulo_id: 2,
            nombre: 'MAIZ MOLIDO ',
            costo_principal: 810,
            precio_principal: 860,
            existencia: 3606695.7699999996,
            aviso_existencia: 1,
            codigo: '00984',
            fecha_ingreso: new Date('2024-04-12'),
            medida: 'Saco',
            is_detallable: true,
            medida_alerta: 'Libra',
            calcular_itbis: false,
            estado: true,
            is_combo: false,
            otros_costos: null,
            vendido_en: 'Saco',
            created_at: '2024-04-12T15:32:05.170Z',
            updated_at: '2025-04-03T11:00:39.666Z',
            is_materia_prima: true,
            calcular_saco: false,
            contenido_articulos: [
              { id: 411, articulo_id: 984, referencia: null, costo: 8.1, precio: 8.6, cantidad: 100, medida: 'Libra', condicion: 'padre', calcular_itbis: null, created_at: '2024-04-12T15:32:05.212Z', updated_at: '2025-03-12T13:15:09.715Z' },
            ],
            formulas_productos_terminados: [],
            descripcion: 'MAIZ MOLIDO ',
          },
          unidad: 'Saco',
          itbis: 0,
          itbis_real: 0,
          costo: 810,
          precio: 860,
          precio_real: 860,
          total: 21500,
          cantidad_en_unidades: 2500,
          cantidad_origin: 50,
          cantidad: 25,
          detalle_factura_id: 150273,
          descuento: 0,
          descuento_real: 0,
        },
        {
          articulo_id: 166,
          articulo: {
            id: 166,
            imagen_id: null,
            tipo_articulo_id: 2,
            nombre: 'TRIGO',
            costo_principal: 585,
            precio_principal: 690,
            existencia: 255927.82,
            aviso_existencia: 30,
            codigo: '00166',
            fecha_ingreso: new Date('2020-11-17'),
            medida: 'Quintal',
            is_detallable: true,
            medida_alerta: 'Quintal',
            calcular_itbis: false,
            estado: true,
            is_combo: false,
            otros_costos: null,
            vendido_en: 'Saco',
            created_at: '2020-11-17T17:00:26.589Z',
            updated_at: '2025-04-03T11:00:39.692Z',
            is_materia_prima: true,
            calcular_saco: true,
            contenido_articulos: [
              { id: 29, articulo_id: 166, referencia: null, costo: 5.85, precio: 6.9, cantidad: 100, medida: 'Libra', condicion: 'padre', calcular_itbis: null, created_at: '2020-11-17T17:00:26.591Z', updated_at: '2024-08-27T15:57:25.418Z' },
            ],
            formulas_productos_terminados: [],
            descripcion: 'TRIGO',
          },
          unidad: 'Saco',
          itbis: 0,
          itbis_real: 0,
          costo: 585,
          precio: 690,
          precio_real: 690,
          total: 6800,
          cantidad_en_unidades: 1000,
          cantidad_origin: 50,
          cantidad: 10,
          detalle_factura_id: 150274,
          descuento: 500,
          descuento_real: 0,
        },
      ],
    },
  ],
};
