import { FacturaI } from '../../core/types/factura.types';

export class ParseDocument {
  constructor() {}

  parse(document: FacturaI) {
    return {
      ECF: {
        Encabezado: {
          Version: '',
          IdDoc: {
            TipoeCF: '',
            eNCF: '',
            FechaVencimientoSecuencia: '',
            IndicadorEnvioDiferido: '',
            IndicadorMontoGravado: '',
            IndicadorServicioTodoIncluido: '',
            TipoIngresos: '',
            TipoPago: '',
            FechaLimitePago: '',
            TerminoPago: '',
            TablaFormasPago: {
              FormaDePago: [],
            },
            TipoCuentaPago: '',
            NumeroCuentaPago: '',
            BancoPago: '',
            FechaDesde: '',
            FechaHasta: '',
            TotalPaginas: '',
          },
          Emisor: {
            RNCEmisor: '',
            RazonSocialEmisor: '',
            NombreComercial: '',
            Sucursal: '',
            DireccionEmisor: '',
            Municipio: '',
            Provincia: '',
            TablaTelefonoEmisor: {
              TelefonoEmisor: [],
            },
            CorreoEmisor: '',
            WebSite: '',
            ActividadEconomica: '',
            CodigoVendedor: '',
            NumeroFacturaInterna: '',
            NumeroPedidoInterno: '',
            ZonaVenta: '',
            RutaVenta: '',
            InformacionAdicionalEmisor: '',
            FechaEmision: '',
          },
          Comprador: {
            RNCComprador: '',
            RazonSocialComprador: '',
            ContactoComprador: '',
            CorreoComprador: '',
            DireccionComprador: '',
            MunicipioComprador: '',
            ProvinciaComprador: '',
            FechaEntrega: '',
            ContactoEntrega: '',
            DireccionEntrega: '',
            TelefonoAdicional: '',
            FechaOrdenCompra: '',
            NumeroOrdenCompra: '',
            CodigoInternoComprador: '',
            ResponsablePago: '',
            InformacionAdicionalComprador: '',
            IdentificadorExtranjero: '',
          },
          InformacionesAdicionales: {
            FechaEmbarque: '',
            NumeroEmbarque: '',
            NumeroContenedor: '',
            NumeroReferencia: '',
            PesoBruto: '',
            PesoNeto: '',
            UnidadPesoBruto: '',
            UnidadPesoNeto: '',
            CantidadBulto: '',
            UnidadBulto: '',
            VolumenBulto: '',
            UnidadVolumen: '',
          },
          Transporte: {
            Conductor: '',
            DocumentoTransporte: '',
            Ficha: '',
            Placa: '',
            RutaTransporte: '',
            ZonaTransporte: '',
            NumeroAlbaran: '',
          },
          Totales: {
            MontoGravadoTotal: '',
            MontoGravadoI1: '',
            MontoGravadoI2: '',
            MontoGravadoI3: '',
            MontoExento: '',
            ITBIS1: '',
            ITBIS2: '',
            ITBIS3: '',
            TotalITBIS: '',
            TotalITBIS1: '',
            TotalITBIS2: '',
            TotalITBIS3: '',
            MontoImpuestoAdicional: '',
            ImpuestosAdicionales: {
              ImpuestoAdicional: [],
            },
            MontoTotal: '',
            MontoNoFacturable: '',
            MontoPeriodo: '',
            SaldoAnterior: '',
            MontoAvancePago: '',
            ValorPagar: '',
            TotalITBISRetenido: '',
            TotalISRRetencion: '',
            TotalITBISPercepcion: '',
            TotalISRPercepcion: '',
          },
          OtraMoneda: {
            TipoMoneda: '',
            TipoCambio: '',
            MontoGravadoTotalOtraMoneda: '',
            MontoGravado1OtraMoneda: '',
            MontoGravado2OtraMoneda: '',
            MontoGravado3OtraMoneda: '',
            MontoExentoOtraMoneda: '',
            TotalITBISOtraMoneda: '',
            TotalITBIS1OtraMoneda: '',
            TotalITBIS2OtraMoneda: '',
            TotalITBIS3OtraMoneda: '',
            MontoImpuestoAdicionalOtraMoneda: '',
            ImpuestosAdicionalesOtraMoneda: {
              ImpuestoAdicionalOtraMoneda: [],
            },
            MontoTotalOtraMoneda: '',
          },
        },
        DetallesItems: {
          Item: [],
        },
        Subtotales: {
          Subtotal: [],
        },
        DescuentosORecargos: {
          DescuentoORecargo: [],
        },
        Paginacion: {
          Pagina: [],
        },
        InformacionReferencia: {
          NCFModificado: '',
          RNCOtroContribuyente: '',
          FechaNCFModificado: '',
          CodigoModificacion: '',
        },
        FechaHoraFirma: '',
      },
    };
  }
}
