FROM node:22.13.1-alpine

WORKDIR /app

# Copiar archivos de dependencias
COPY package*.json ./
COPY tsconfig.json ./

# Instalar todas las dependencias (incluyendo devDependencies)
RUN npm install

# Crear un archivo .env para desarrollo si es necesario
RUN echo "ENV=DEV" > .env

# Exponer puerto
EXPOSE 9091

# Montar el código fuente (se hará mediante un volumen en docker-compose)
# No es necesario copiar el código fuente aquí ya que se montará como volumen

# Comando para iniciar el servicio en modo desarrollo
CMD ["npm", "run", "start:dev"] 